// Lista generi estesa
const genres = [
  { id: "pop", name: "Pop" },
  { id: "rock", name: "Rock" },
  { id: "hip-hop", name: "Hip-Hop" },
  { id: "classical", name: "Classica" },
  { id: "acoustic", name: "Acustica" },
  { id: "piano", name: "Piano" },
  { id: "instrumental", name: "Strumentale" },
  { id: "edm", name: "EDM" },
  { id: "indie", name: "Indie" },
  { id: "trap", name: "Trap" },
  { id: "jazz", name: "Jazz" },
  { id: "funk", name: "Funk" },
  { id: "soul", name: "Soul" },
  { id: "metal", name: "Metal" },
  { id: "reggae", name: "Reggae" },
  { id: "rnb", name: "R&B" },
  { id: "country", name: "Country" },
  { id: "blues", name: "Blues" },
  { id: "folk", name: "Folk" },
  { id: "disco", name: "Disco" },
  { id: "techno", name: "Techno" },
  { id: "house", name: "House" },
  { id: "dubstep", name: "Dubstep" },
  { id: "ambient", name: "Ambient" },
  { id: "k-pop", name: "K-Pop" },
  { id: "latin", name: "Latin" },
  { id: "funky", name: "Funky" },
  { id: "electro", name: "Electro" },
  { id: "drum-n-bass", name: "Drum & Bass" },
  { id: "opera", name: "Opera" }
];